# Generated by Django 6.1 on 2026-08-29 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('RECRUITER', 'Recruiter'), ('HR', 'HR')], max_length=40),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
