# Generated by Django 6.1 on 2026-09-07 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.CharField(default='', max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='applicantResume/')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWING', 'Reviewing'), ('SHORTLISTED', 'Short Listed'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='unique_application')],
            },
        ),
    ]
